# -*- coding: utf-8 -*-
# @Author       : AaronJny
# @LastEditTime : 2021-03-12
# @FilePath     : /deeparts/deeparts/core/models/image.py
# @Desc         : 图像处理相关模型
from deeparts.core.models.classifier import (
    deepartsLeNetImageClassifier,
    deepartsDenseNet121ImageClassifier,
    deepartsDenseNet169ImageClassifier,
    deepartsDenseNet201ImageClassifier,
    deepartsVGG16ImageClassifier,
    deepartsVGG19ImageClassifier,
    deepartsMobileNetImageClassifier,
    deepartsMobileNetV2ImageClassifier,
    deepartsInceptionResNetV2ImageClassifier,
    deepartsInceptionV3ImageClassifier,
    deepartsNASNetMobileImageClassifier,
    deepartsNASNetLargeImageClassifier,
    deepartsResNet50ImageClassifier,
    deepartsResNet50V2ImageClassifier,
    deepartsResNet101ImageClassifier,
    deepartsResNet101V2ImageClassifier,
    deepartsResNet152ImageClassifier,
    deepartsResNet152V2ImageClassifier,
    deepartsMobileNetV3SmallImageClassifier,
    deepartsMobileNetV3LargeImageClassifier,
    deepartsXceptionImageClassifier,
    deepartsEfficientNetB0ImageClassifier,
    deepartsEfficientNetB1ImageClassifier,
    deepartsEfficientNetB2ImageClassifier,
    deepartsEfficientNetB3ImageClassifier,
    deepartsEfficientNetB4ImageClassifier,
    deepartsEfficientNetB5ImageClassifier,
    deepartsEfficientNetB6ImageClassifier,
    deepartsEfficientNetB7ImageClassifier,
)
from deeparts.core.models.complex.od.models import deepartsTFModelsObjectDetector

pre_trained_classifiers = [
    deepartsLeNetImageClassifier,
    deepartsDenseNet121ImageClassifier,
    deepartsDenseNet169ImageClassifier,
    deepartsDenseNet201ImageClassifier,
    deepartsVGG16ImageClassifier,
    deepartsVGG19ImageClassifier,
    deepartsMobileNetImageClassifier,
    deepartsMobileNetV2ImageClassifier,
    deepartsInceptionResNetV2ImageClassifier,
    deepartsInceptionV3ImageClassifier,
    deepartsNASNetMobileImageClassifier,
    deepartsNASNetLargeImageClassifier,
    deepartsResNet50ImageClassifier,
    deepartsResNet50V2ImageClassifier,
    deepartsResNet101ImageClassifier,
    deepartsResNet101V2ImageClassifier,
    deepartsResNet152ImageClassifier,
    deepartsResNet152V2ImageClassifier,
    deepartsMobileNetV3SmallImageClassifier,
    deepartsMobileNetV3LargeImageClassifier,
    deepartsXceptionImageClassifier,
    deepartsEfficientNetB0ImageClassifier,
    deepartsEfficientNetB1ImageClassifier,
    deepartsEfficientNetB2ImageClassifier,
    deepartsEfficientNetB3ImageClassifier,
    deepartsEfficientNetB4ImageClassifier,
    deepartsEfficientNetB5ImageClassifier,
    deepartsEfficientNetB6ImageClassifier,
    deepartsEfficientNetB7ImageClassifier,
]
tf_models_detectors = [
    deepartsTFModelsObjectDetector,
]

__all__ = [
    "deepartsLeNetImageClassifier",
    "deepartsDenseNet121ImageClassifier",
    "deepartsDenseNet169ImageClassifier",
    "deepartsDenseNet201ImageClassifier",
    "deepartsVGG16ImageClassifier",
    "deepartsVGG19ImageClassifier",
    "deepartsMobileNetImageClassifier",
    "deepartsMobileNetV2ImageClassifier",
    "deepartsInceptionResNetV2ImageClassifier",
    "deepartsInceptionV3ImageClassifier",
    "deepartsNASNetMobileImageClassifier",
    "deepartsNASNetLargeImageClassifier",
    "deepartsResNet50ImageClassifier",
    "deepartsResNet50V2ImageClassifier",
    "deepartsResNet101ImageClassifier",
    "deepartsResNet101V2ImageClassifier",
    "deepartsResNet152ImageClassifier",
    "deepartsResNet152V2ImageClassifier",
    "deepartsMobileNetV3SmallImageClassifier",
    "deepartsMobileNetV3LargeImageClassifier",
    "deepartsXceptionImageClassifier",
    "deepartsEfficientNetB0ImageClassifier",
    "deepartsEfficientNetB1ImageClassifier",
    "deepartsEfficientNetB2ImageClassifier",
    "deepartsEfficientNetB3ImageClassifier",
    "deepartsEfficientNetB4ImageClassifier",
    "deepartsEfficientNetB5ImageClassifier",
    "deepartsEfficientNetB6ImageClassifier",
    "deepartsEfficientNetB7ImageClassifier",
    "pre_trained_classifiers",
    "deepartsTFModelsObjectDetector",
    "tf_models_detectors",
]